import { NavigationItem } from './navigation-item.model';

export const NAVIGATION_ITEMS: readonly NavigationItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: 'dashboard',
    route: '/dashboard',
    permission: 'DASHBOARD_VIEW',
  },
  {
    id: 'members',
    label: 'Membros',
    icon: 'groups',
    route: '/members',
    permission: 'MEMBER_VIEW',
  },
  {
    id: 'memberships',
    label: 'Membresias',
    icon: 'how_to_reg',
    route: '/memberships',
    permission: 'MEMBERSHIP_VIEW',
  },
  {
    id: 'organization',
    label: 'Organização',
    icon: 'account_tree',
    children: [
      {
        id: 'churches',
        label: 'Igrejas',
        icon: 'church',
        route: '/organization/churches',
        permission: 'CHURCH_VIEW',
      },
      {
        id: 'departments',
        label: 'Departamentos',
        icon: 'diversity_3',
        route: '/organization/departments',
        permission: 'DEPARTMENT_VIEW',
      },
      {
        id: 'leaders',
        label: 'Lideranças',
        icon: 'supervisor_account',
        route: '/organization/leaders',
        permission: 'DEPARTMENT_LEADER_VIEW',
      },
      {
        id: 'church-roles',
        label: 'Cargos eclesiásticos',
        icon: 'workspace_premium',
        route: '/organization/church-roles',
        permission: 'CHURCH_ROLE_VIEW',
      },
    ],
  },
  {
    id: 'reports',
    label: 'Relatórios',
    icon: 'assessment',
    route: '/reports',
    permission: 'REPORT_VIEW',
  },
  {
    id: 'administration',
    label: 'Administração',
    icon: 'admin_panel_settings',
    children: [
      {
        id: 'accounts',
        label: 'Usuários',
        icon: 'manage_accounts',
        route: '/administration/accounts',
        permission: 'ACCOUNT_VIEW',
      },
      {
        id: 'account-profiles',
        label: 'Perfis de acesso',
        icon: 'badge',
        route: '/administration/account-profiles',
        permission: 'ACCOUNT_PROFILE_VIEW',
      },
    ],
  },
  {
    id: 'auxiliary-data',
    label: 'Cadastros Auxiliares',
    icon: 'tune',
    children: [
      {
        id: 'genders',
        label: 'Gêneros',
        icon: 'wc',
        route: '/auxiliary-data/genders',
        permission: 'GENDER_VIEW',
      },
      {
        id: 'marital-statuses',
        label: 'Estados civis',
        icon: 'favorite',
        route: '/auxiliary-data/marital-statuses',
        permission: 'MARITAL_STATUS_VIEW',
      },
      {
        id: 'address-types',
        label: 'Tipos de endereço',
        icon: 'home_pin',
        route: '/auxiliary-data/address-types',
        permission: 'ADDRESS_TYPE_VIEW',
      },
      {
        id: 'phone-types',
        label: 'Tipos de telefone',
        icon: 'phone',
        route: '/auxiliary-data/phone-types',
        permission: 'PHONE_TYPE_VIEW',
      },
      {
        id: 'education-levels',
        label: 'Níveis de escolaridade',
        icon: 'school',
        route: '/auxiliary-data/education-levels',
        permission: 'EDUCATION_LEVEL_VIEW',
      },
      {
        id: 'formation-areas',
        label: 'Áreas de formação',
        icon: 'menu_book',
        route: '/auxiliary-data/formation-areas',
        permission: 'FORMATION_AREA_VIEW',
      },
      {
        id: 'professions',
        label: 'Profissões',
        icon: 'work',
        route: '/auxiliary-data/professions',
        permission: 'PROFESSION_VIEW',
      },
      {
        id: 'membership-statuses',
        label: 'Situações da membresia',
        icon: 'fact_check',
        route: '/auxiliary-data/membership-statuses',
        permission: 'MEMBERSHIP_STATUS_VIEW',
      },
      {
        id: 'religious-origins',
        label: 'Origens religiosas',
        icon: 'history_edu',
        route: '/auxiliary-data/religious-origins',
        permission: 'RELIGIOUS_ORIGIN_VIEW',
      },
      {
        id: 'leader-types',
        label: 'Tipos de liderança',
        icon: 'record_voice_over',
        route: '/auxiliary-data/leader-types',
        permission: 'LEADER_TYPE_VIEW',
      },
    ],
  },
];
